package ee.joonasvali.spaceblaster.event;

public enum EventType {
  PLAYER_KILLED,
  PLAYER_BORN,
  PLAYER_NO_LONGER_INVINCIBLE,
  ENEMY_KILLED,
  ENEMY_HIT,
  POWERUP_COLLECTED,
  POWERUP_MISSED,
  POWERUP_CREATED,
  ENEMY_FORMATION_CHANGES_MOVEMENT_DIRECTION,
  VICTORY,
  LEVEL_COMPLETED,
  GAME_OVER,
  LOAD_LEVEL,
  START_GAME
}
